from Safety_areas.safety_areas import Rand, AFZETTINGEN

aanvragen = {
    "Categorie A links": {
        "km": [16.1, 16.6],
        "wegkant": "R",
        "hectoletter": "",
        "korter_dan_24h": True,
        "randen": {"L": Rand(rijstrook=None, afstand=-1.8), "R": Rand(rijstrook=None, afstand=-1.2)},
        "afzetting": AFZETTINGEN.BAKENS,
    },
    "Categorie A rechts": {
        "km": [16.1, 16.6],
        "wegkant": "R",
        "hectoletter": "",
        "korter_dan_24h": True,
        "randen": {"L": Rand(rijstrook=None, afstand=1.2), "R": Rand(rijstrook=None, afstand=1.8)},
        "afzetting": AFZETTINGEN.BAKENS,
    },
    "Categorie B links": {
        "km": [16.1, 16.6],
        "wegkant": "R",
        "hectoletter": "",
        "korter_dan_24h": True,
        "randen": {"L": Rand(rijstrook=None, afstand=-1.0), "R": Rand(rijstrook=None, afstand=-0.2)},
        "afzetting": AFZETTINGEN.BAKENS,
    },
    "Categorie B rechts": {
        "km": [16.1, 16.6],
        "wegkant": "R",
        "hectoletter": "",
        "korter_dan_24h": True,
        "randen": {"L": Rand(rijstrook=None, afstand=0.2),
                   "R": Rand(rijstrook=None, afstand=1.0)},
        "afzetting": AFZETTINGEN.BAKENS,
    },
    "Categorie C links": {
        "km": [16.1, 16.6],
        "wegkant": "R",
        "hectoletter": "",
        "korter_dan_24h": False,
        "randen": {"L": Rand(rijstrook=None, afstand=-1.0),
                   "R": Rand(rijstrook=None, afstand=-0.22)},
        "afzetting": AFZETTINGEN.BAKENS,
    },
    "Categorie C rechts": {
        "km": [16.1, 16.6],
        "wegkant": "R",
        "hectoletter": "",
        "korter_dan_24h": False,
        "randen": {"L": Rand(rijstrook=None, afstand=0.22),
                   "R": Rand(rijstrook=None, afstand=1.0)},
        "afzetting": AFZETTINGEN.BAKENS,
    },
    "Categorie D links": {
        "km": [16.1, 16.6],
        "wegkant": "R",
        "hectoletter": "",
        "korter_dan_24h": True,
        "randen": {"L": Rand(rijstrook=1, afstand=0.3),
                   "R": Rand(rijstrook=1, afstand=-1.1)},
        "afzetting": AFZETTINGEN.BAKENS,
    },
    "Categorie D rechts": {
        "km": [16.1, 16.6],
        "wegkant": "R",
        "hectoletter": "",
        "korter_dan_24h": True,
        "randen": {"L": Rand(rijstrook=2, afstand=1.1),
                   "R": Rand(rijstrook=2, afstand=-0.3)},
        "afzetting": AFZETTINGEN.BAKENS,
    },
    "Categorie A links met barriers": {
        "km": [16.1, 16.6],
        "wegkant": "R",
        "hectoletter": "",
        "korter_dan_24h": False,
        "randen": {"L": Rand(rijstrook=None, afstand=-1.8),
                   "R": Rand(rijstrook=None, afstand=-0.4)},
        "afzetting": AFZETTINGEN.BARRIER_BOVEN_80CM,
    },
}
